# -*- encoding: utf-8 -*-

=begin
#Edmentum Web API - v2.0

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v2

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.33

=end

$:.push File.expand_path("../lib", __FILE__)
require "edmentum_client/version"

Gem::Specification.new do |s|
  s.name        = "edmentum-client"
  s.version     = EdmentumClient::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["Mark Ng", "Paul Shippy", "Mike Benner"]
  s.email       = ["teambelding@strongmind.com"]
  s.homepage    = "https://github.com/StrongMind/edmentum-client-ruby"
  s.summary     = "Edmentum Web API - v2.0 Ruby Gem"
  s.description = "A client for accessing Edmentum's 2.0 APIs. Not authored by Edmentum."
  s.license     = "MIT"
  s.required_ruby_version = ">= 1.9"

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'
  s.add_runtime_dependency 'json', '~> 2.1', '>= 2.1.0'
  s.add_runtime_dependency 'addressable', '~> 2.3', '>= 2.3.0'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'
  s.add_development_dependency 'vcr', '~> 3.0', '>= 3.0.1'
  s.add_development_dependency 'webmock', '~> 1.24', '>= 1.24.3'
  s.add_development_dependency 'autotest', '~> 4.4', '>= 4.4.6'
  s.add_development_dependency 'autotest-rails-pure', '~> 4.1', '>= 4.1.2'
  s.add_development_dependency 'autotest-growl', '~> 0.2', '>= 0.2.16'

  s.files         = `find * | grep -v .gem`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
