=begin
#Edmentum Web API - v2.0

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v2

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.33

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::V20ExactPathApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'V20ExactPathApi' do
  before do
    # run before each test
    @instance = EdmentumClient::V20ExactPathApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of V20ExactPathApi' do
    it 'should create an instance of V20ExactPathApi' do
      expect(@instance).to be_instance_of(EdmentumClient::V20ExactPathApi)
    end
  end

  # unit tests for classes_controller_create_exact_path_class
  # Create a new Exact Path Class
  # @param model The model for the class to be created.              &lt;br /&gt;ClassGrade, ClassExpirationDate, CloseoutReminderDate and Location are optional.              &lt;br /&gt;AllowSelfEnrollment is optional and will default to false.              &lt;br /&gt;Program ID is ignored during class creation              &lt;br /&gt;At least one instructor ID is required.              &lt;br /&gt;Learners are optional.
  # @param [Hash] opts the optional parameters
  # @return [EdApiModelsExactPathClass]
  describe 'classes_controller_create_exact_path_class test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for classes_controller_delete_exact_path_class
  # Delete a Exact Path Class by Class ID
  # @param class_id The id of the class to delete.  If class has active assignments, the class will be archived.
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'classes_controller_delete_exact_path_class test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for classes_controller_enroll_learner_in_class
  # Enroll learner into Exact Path Class
  # @param class_id The id of the class to add the learner.
  # @param learner_id The user ID of the learner to enroll in the class.
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'classes_controller_enroll_learner_in_class test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for classes_controller_get_exact_path_class
  # Get a Exact Path Class by Class ID
  # @param class_id The id of the class to retrieve.
  # @param [Hash] opts the optional parameters
  # @return [EdApiModelsExactPathClass]
  describe 'classes_controller_get_exact_path_class test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for classes_controller_get_exact_path_class_learners
  # Get a simplified data set of learners enrolled in an Exact Path Class by Class ID.
  # &lt;ul&gt;    &lt;li&gt;Gender can be 0 (male) or 1 (female).&lt;/li&gt;    &lt;li&gt;Grade is 0-15 with 0 being kindergarten and 13-15 adult values that are invalid for learners.&lt;/li&gt;    &lt;li&gt;Birth date is date only so will always be 0&#39;s for time.&lt;/li&gt;  &lt;/ul&gt;
  # @param class_id The Class ID
  # @param [Hash] opts the optional parameters
  # @return [Array<EdApiModelsExactPathClassLearner>]
  describe 'classes_controller_get_exact_path_class_learners test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for classes_controller_get_time_spent_in_learning_path
  # Get the learning path progress report for a subject by date range for the current academic year.
  # @param class_id The Class ID
  # @param model The query model for the report containing the ID for the subject (Valid entries are: 5 &#x3D; Math, 4 &#x3D; Language Arts, 15 &#x3D; Reading.),              &lt;br /&gt;the starting date for the report results and the the end date for the range of results.
  # @param [Hash] opts the optional parameters
  # @return [EdApiModelsExactPathLearningPathProgressReport]
  describe 'classes_controller_get_time_spent_in_learning_path test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for classes_controller_remove_learner_from_class
  # Remove a learner from a Exact Path Class
  # @param class_id The id of the class.
  # @param learner_id The user ID of the learner to remove from the class.
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'classes_controller_remove_learner_from_class test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for classes_controller_update_exact_path_class
  # Update Exact Path Class
  # @param model The model for the class to be created.              &lt;br /&gt;ClassId is required.              &lt;br /&gt;ClassGrade, ClassExpirationDate, CloseoutReminderDate and Location are optional.              &lt;br /&gt;AllowSelfEnrollment is optional and will default to false.              &lt;br /&gt;Program ID is ignored during class creation              &lt;br /&gt;At least one instructor ID is required.              &lt;br /&gt;Learners are optional.
  # @param [Hash] opts the optional parameters
  # @return [EdApiModelsExactPathClass]
  describe 'classes_controller_update_exact_path_class test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
